server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: wepay-promotion-backend
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000ms
    password:
  jackson:
    default-property-inclusion: non_null

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wepay.promotion.entity
  configuration:
    map-underscore-to-camel-case: true

# ShardingSphere 配置已移至 shardingsphere.yaml
# 由 ShardingSphereConfig.java 加载创建 DataSource Bean
wx:
  miniapp:
    appid: wxefa531580e370957
    secret: ba700ff366edfce3dc628ddb8ebdd978
  pay:
    mch-id: 1749127860
    mch-key: LPfhyebbjuOI158328OWCVghspoumqwv
    notify-url: http://nj409uu6213.vicp.fun/api/pay/notify
    cert-path: D:/Users/clinton/Downloads/cert/apiclient_cert.p12
    transfer-desc: 文章分享佣金

logging:
  level:
    com.wepay.promotion: debug
    org.apache.shardingsphere: debug
